#!/usr/bin/env bash
# This script transfers a file from our client to a server using the scp command

if [ $# -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    file_path=$1
    server_ip=$2
    user_name=$3
    ssh_key=$4

    scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$user_name"@"$server_ip":~/
fi
