#!/usr/bin/env bash
#Update the packet list
sudo apt-get -y update
#Install nginx
sudo apt-get -y install nginx
#Start nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.html'
service nginx start
