#!/usr/bin/env bash
# update the packet list
sudo apt-get update -y
#install nginx
apt-get install nginx -y

#configure the Nginx server to makes it listen tk port 80
echo "Hello Wolrd!" > /var/www/html/index.html

#Restart the server
service nginx start
