#!/usr/bin/env bash
# print Best School 10 times then Hi
h=0
while ((h <= 12))
do
    echo "Hour: $h"

    min=1
    while ((min < 60))
    do
	echo "$min"
	min=$((min+1))
    done
    h=$((h+1))
done