#!/usr/bin/env bash
# a script that installs ufw (firewall ) and writing its rules

sudo apt update -y
sudo install ufw -y
sudo ufw defalut deny incoming
sudo ufw default allow outgoing
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp
sudo ufw allow 22/tcp
sudo ufw enable
